# Generated by Django 5.2.6 on 2025-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre o Alias de la Unidad'),
            preserve_default=False,
        ),
    ]
