# Generated by Django 5.2.6 on 2025-09-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_unidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre o Alias de la Unidad'),
        ),
    ]
