# Generated by Django 5.2.6 on 2025-09-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_alter_unidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargadiesel',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendimiento (Km/L)'),
        ),
        migrations.AddField(
            model_name='cargaurea',
            name='rendimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Rendimiento (Km/L)'),
        ),
    ]
