# Generated by Django 5.2.6 on 2025-10-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_cargadiesel_rendimiento_cargaurea_rendimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlantasInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('km', models.PositiveIntegerField(verbose_name='Kilometraje en Inspección')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_llantas', to='flota.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='LlantaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=50, verbose_name='Posición')),
                ('mm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='MM')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('medida', models.CharField(max_length=50, verbose_name='Medida de Llanta')),
                ('presion', models.PositiveIntegerField(verbose_name='Presión (PSI)')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_llanta', to='flota.llantasinspeccion')),
            ],
        ),
    ]
