# Generated by Django 5.2.6 on 2025-10-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_llantasinspeccion_llantadetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargadiesel',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Total'),
        ),
    ]
