# Generated by Django 5.2.6 on 2025-10-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_cargadiesel_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaurea',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('S', 'Seca'), ('R', 'Refrigerada'), ('A', 'Ambas (Refrigerada/Seca)')], default='S', max_length=1),
        ),
    ]
