# Generated by Django 5.2.6 on 2025-10-11 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_cargaurea_costo_alter_unidad_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('S', 'Seca'), ('R', 'Refrigerada'), ('A', 'Refrigerada/Seca')], default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='ProcesoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Carga'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=10)),
                ('carga_diesel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.cargadiesel')),
                ('carga_urea', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.cargaurea')),
                ('checklist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flota.checklistinspeccion')),
                ('encargado_finaliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_finalizados', to=settings.AUTH_USER_MODEL)),
                ('inspeccion_llantas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flota.llantasinspeccion')),
                ('tecnico_inicia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_iniciados', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos_carga', to='flota.unidad')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
