# Generated by Django 5.2.6 on 2025-10-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_alter_unidad_tipo_procesocarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinspeccion',
            name='amortiguadores_delanteros_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Amortiguadores Del.'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='amortiguadores_traseros_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Amortiguadores Tras.'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='caja_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Caja'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='carroceria_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Carrocería'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='cofre_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Cofre'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='costados_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Costados'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='cristales_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Cristales'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='defensas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Defensas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='diferenciales_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Diferenciales'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='direccionales_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Direccionales'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='escape_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Escape'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='espejos_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Espejos'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='estado_balatas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Estado Balatas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='estado_general_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Estado General'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='estado_llantas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Estado Llantas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='extintor_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Extintor'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='faros_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Faros'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='franjas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Franjas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='fugas_aceite_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Fugas Aceite'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='fugas_combustible_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Fugas Combustible'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='instrumentos_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Instrumentos'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='loderas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Loderas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='logos_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Logos'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='mangueras_servicio_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Mangueras Servicio'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='motor_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Motor'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='num_economico_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Núm. Económico'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='parrilla_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Parrilla'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='pintura_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Pintura'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='piso_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Piso'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='plafoneria_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Plafonería'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='presion_llantas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Presión Llantas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='puertas_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Puertas'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='purga_tanques_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Purga Tanques'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='revision_cable_7vias_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Revisión Cable 7 Vías'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='revision_fuga_aire_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Revisión Fuga de Aire'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='revision_fusibles_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Revisión Fusibles'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='revision_luces_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Revisión Luces'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='rines_aluminio_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Rines Aluminio'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='senalamientos_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Señalamientos'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='stops_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Stops'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='suspension_delantera_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Suspensión Del.'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='suspension_trasera_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Suspensión Tras.'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='tapiceria_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Tapicería'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='tarjeta_llave_foto',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_evidencia/', verbose_name='Foto Tarjeta Llave'),
        ),
    ]
