# Generated by Django 5.2.6 on 2025-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_checklistinspeccion_amortiguadores_delanteros_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprasuministro',
            name='litros_restantes',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, help_text='Litros disponibles de esta compra', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comprasuministro',
            name='precio_por_litro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio por Litro/Unidad'),
        ),
        migrations.AlterField(
            model_name='cargadiesel',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='cargaurea',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='comprasuministro',
            name='precio',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Precio Total'),
        ),
    ]
