# Generated by Django 5.2.6 on 2025-10-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0010_comprasuministro_litros_restantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasuministro',
            name='fecha_compra',
            field=models.DateTimeField(),
        ),
    ]
