# Generated by Django 5.1.7 on 2025-10-17 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0011_alter_comprasuministro_fecha_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_suministro', models.CharField(choices=[('DIESEL', 'Diésel'), ('UREA', 'Urea'), ('ACEITE', 'Aceite')], max_length=10, verbose_name='Suministro a Ajustar')),
                ('tipo_ajuste', models.CharField(choices=[('ENTRADA', 'Entrada (Sobrante)'), ('SALIDA', 'Salida (Faltante)')], max_length=10, verbose_name='Tipo de Ajuste')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Litros a ajustar (siempre en positivo)', max_digits=10)),
                ('motivo', models.TextField(help_text='Ej: Conteo físico, derrame, merma, etc.')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
