# Generated by Django 5.2.6 on 2025-10-17 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0012_ajusteinventario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField(verbose_name='Fecha de Revisión')),
                ('tecnico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.unidad', verbose_name='Unidad Asignada')),
            ],
            options={
                'verbose_name': 'Asignación de Revisión',
                'verbose_name_plural': 'Asignaciones de Revisión',
                'ordering': ['fecha_revision', 'unidad__nombre'],
                'unique_together': {('unidad', 'fecha_revision')},
            },
        ),
    ]
