# Generated by Django 5.2.6 on 2025-10-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0013_asignacionrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionrevision',
            name='comentario_cancelacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='asignacionrevision',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('NO_VINO', 'No Vino')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
    ]
