# Generated by Django 5.2.6 on 2025-10-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0014_asignacionrevision_comentario_cancelacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_suministro', models.CharField(choices=[('DIESEL', 'Diésel'), ('UREA', 'Urea'), ('ACEITE', 'Aceite')], max_length=10, unique=True, verbose_name='Tipo de Suministro')),
                ('activa', models.BooleanField(default=False, help_text='Indica si la alerta por bajo inventario está actualmente activa.')),
                ('ultimo_aviso', models.DateTimeField(blank=True, help_text='Fecha y hora del último aviso enviado.', null=True)),
                ('nivel_reportado', models.DecimalField(blank=True, decimal_places=2, help_text='El nivel de inventario que disparó la alerta.', max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
            },
        ),
    ]
