# Generated by Django 5.2.7 on 2025-10-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0015_alertainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
