# Generated by Django 5.1.7 on 2025-10-23 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0016_unidad_ultima_actualizacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionrevision',
            name='tecnico_asignado',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='observaciones_generales',
        ),
        migrations.CreateModel(
            name='ChecklistCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=50, verbose_name='Ítem del Checklist')),
                ('observacion_original', models.TextField(blank=True, null=True, verbose_name='Observación original del técnico')),
                ('esta_corregido', models.BooleanField(default=False, verbose_name='Corregido (Admin)')),
                ('comentario_admin', models.TextField(blank=True, null=True, verbose_name='Comentario del Administrador')),
                ('fecha_correccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Corrección')),
                ('corregido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_checklist', to=settings.AUTH_USER_MODEL, verbose_name='Administrador que corrigió')),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='flota.checklistinspeccion')),
            ],
            options={
                'verbose_name': 'Corrección de Checklist',
                'verbose_name_plural': 'Correcciones de Checklist',
                'unique_together': {('inspeccion', 'nombre_campo')},
            },
        ),
    ]
