# Generated by Django 5.1.7 on 2025-10-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0017_remove_asignacionrevision_tecnico_asignado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='flota.asignacionrevision')),
            ],
        ),
    ]
