# Generated by Django 5.1.7 on 2025-10-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0019_alter_asignacionrevision_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionrevision',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado'), ('NO_VINO', 'No Vino')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
    ]
