# Generated by Django 5.2.7 on 2025-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0020_alter_asignacionrevision_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistcorreccion',
            name='esta_corregido',
        ),
        migrations.AddField(
            model_name='checklistcorreccion',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CORREGIDO', 'Corregido (Reparado)'), ('DESCARTADO', 'Descartado (Admin)')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='checklistcorreccion',
            name='fecha_correccion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Corrección/Descarte'),
        ),
        migrations.DeleteModel(
            name='ProcesoRevision',
        ),
    ]
