# Generated by Django 5.2.7 on 2025-10-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0021_remove_checklistcorreccion_esta_corregido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargadiesel',
            name='foto_motor',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_diesel/motor/', verbose_name='Foto Motor'),
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='foto_thermo',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_diesel/thermo/', verbose_name='Foto Thermo'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_odometro',
            field=models.ImageField(default=1, upload_to='checklist_odometros/', verbose_name='Foto Odómetro (KM)'),
            preserve_default=False,
        ),
    ]
