# Generated by Django 5.2.7 on 2025-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0022_cargadiesel_foto_motor_cargadiesel_foto_thermo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistcorreccion',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_correcciones/', verbose_name='Foto de Evidencia'),
        ),
    ]
