# Generated by Django 5.2.7 on 2025-10-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0023_checklistcorreccion_foto_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_thermo_hrs/', verbose_name='Foto Horas Thermo'),
        ),
    ]
