# Generated by Django 5.2.7 on 2025-10-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0024_checklistinspeccion_foto_thermo_hrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_odometro',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
        ),
        migrations.AddField(
            model_name='cargadiesel',
            name='foto_urea',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_urea/', verbose_name='Foto Bomba Urea'),
        ),
        migrations.AddField(
            model_name='cargaurea',
            name='foto_urea',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_urea/', verbose_name='Foto Bomba Urea'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_motor',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_diesel/motor/', verbose_name='Foto Bomba Diésel Motor'),
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_thermo',
            field=models.ImageField(blank=True, null=True, upload_to='cargas_diesel/thermo/', verbose_name='Foto Bomba Diésel Thermo'),
        ),
    ]
