# Generated by Django 5.2.7 on 2025-10-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0025_remove_checklistinspeccion_foto_odometro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargadiesel',
            name='foto_urea',
        ),
    ]
