# Generated by Django 5.2.7 on 2025-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0026_remove_cargadiesel_foto_urea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_motor',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='foto_thermo',
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_odometro',
            field=models.ImageField(default=1, upload_to='checklist_odometros/', verbose_name='Foto Odómetro (KM)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
            field=models.ImageField(default=1, upload_to='checklist_thermo_hrs/', verbose_name='Foto Horas Thermo'),
            preserve_default=False,
        ),
    ]
