# Generated by Django 5.2.7 on 2025-10-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0027_remove_checklistinspeccion_foto_motor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_thermo_hrs/', verbose_name='Foto Horas Thermo'),
        ),
    ]
