# Generated by Django 5.2.7 on 2025-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0028_alter_checklistinspeccion_foto_thermo_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinspeccion',
            name='foto_sticker',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_stickers/', verbose_name='Foto Sticker'),
        ),
        migrations.AlterField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
            field=models.ImageField(default=1, upload_to='checklist_thermo_hrs/', verbose_name='Foto Horas Thermo'),
            preserve_default=False,
        ),
    ]
