# Generated by Django 5.2.7 on 2025-10-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0029_checklistinspeccion_foto_sticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinspeccion',
            name='foto_sticker',
            field=models.ImageField(default=1, upload_to='checklist_stickers/', verbose_name='Foto Sticker'),
            preserve_default=False,
        ),
    ]
