# Generated by Django 5.2.7 on 2025-10-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0030_alter_checklistinspeccion_foto_sticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='revision_cable_7vias',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='revision_cable_7vias_foto',
        ),
        migrations.RemoveField(
            model_name='checklistinspeccion',
            name='revision_cable_7vias_obs',
        ),
    ]
