# Generated by Django 5.2.7 on 2025-10-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0031_remove_checklistinspeccion_revision_cable_7vias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistinspeccion',
            name='foto_odometro',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_odometros/', verbose_name='Foto Odómetro (KM)'),
        ),
        migrations.AlterField(
            model_name='checklistinspeccion',
            name='foto_sticker',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_stickers/', verbose_name='Foto Sticker'),
        ),
        migrations.AlterField(
            model_name='checklistinspeccion',
            name='foto_thermo_hrs',
            field=models.ImageField(blank=True, null=True, upload_to='checklist_thermo_hrs/', verbose_name='Foto Horas Thermo'),
        ),
    ]
