# Generated by Django 5.2.7 on 2025-10-29 22:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0032_alter_checklistinspeccion_foto_odometro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaSuministros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Entrega')),
                ('cant_cinchos', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Cinchos')),
                ('folio_inicial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Folio Inicial (Cinchos)')),
                ('folio_final', models.PositiveIntegerField(blank=True, null=True, verbose_name='Folio Final (Cinchos)')),
                ('numero_tarjeta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tarjeta (Número o Folio)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('entregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por')),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.operador', verbose_name='Nombre de quien recibe')),
            ],
            options={
                'verbose_name': 'Entrega de Suministro',
                'verbose_name_plural': 'Entregas de Suministros',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
