# Generated by Django 5.2.7 on 2025-10-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0033_entregasuministros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregasuministros',
            name='numero_tarjeta',
        ),
        migrations.AddField(
            model_name='entregasuministros',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AddField(
            model_name='entregasuministros',
            name='tipo_entrega',
            field=models.CharField(blank=True, choices=[('MOTOR', 'Motor'), ('THERMO', 'Thermo')], max_length=10, null=True, verbose_name='Tipo (Motor/Thermo)'),
        ),
        migrations.AddField(
            model_name='entregasuministros',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.unidad', verbose_name='Número de Unidad'),
        ),
    ]
