# Generated by Django 5.2.7 on 2025-10-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0034_remove_entregasuministros_numero_tarjeta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregasuministros',
            name='tipo_entrega',
        ),
        migrations.AddField(
            model_name='entregasuministros',
            name='para_motor',
            field=models.BooleanField(default=False, verbose_name='Para Motor'),
        ),
        migrations.AddField(
            model_name='entregasuministros',
            name='para_thermo',
            field=models.BooleanField(default=False, verbose_name='Para Thermo'),
        ),
    ]
