# Generated by Django 5.2.7 on 2025-10-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0035_remove_entregasuministros_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='capacidad_total_tanque',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usar solo si el combustible es compartido.', max_digits=8, null=True, verbose_name='Capacidad Total Tanque (Si es Compartido)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='combustible_compartido',
            field=models.BooleanField(default=False, verbose_name='Tanque de Combustible Compartido'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='tamano_caja_pies',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño de Caja (Pies)'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='thermo_marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thermo: Marca'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='thermo_modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thermo: Modelo'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='thermo_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thermo: Serie'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='thermo_tipo_cierre',
            field=models.CharField(blank=True, choices=[('PUERTA', 'Puerta'), ('CORTINA', 'Cortina')], max_length=10, null=True, verbose_name='Thermo: Tipo de Cierre'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='total_tanque_diesel_motor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usar solo si NO es compartido.', max_digits=8, null=True, verbose_name='Total Tanque Diésel Motor'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='total_tanque_diesel_thermo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usar solo si NO es compartido.', max_digits=8, null=True, verbose_name='Total Tanque Diésel Thermo'),
        ),
    ]
