# Generated by Django 5.2.7 on 2025-10-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0036_unidad_capacidad_total_tanque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='cantidad_cilindros',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Cilindros'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='tipo_combustible',
            field=models.CharField(choices=[('DIESEL', 'Diésel'), ('GASOLINA', 'Gasolina')], default='DIESEL', max_length=10, verbose_name='Tipo de Combustible'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='unidad_negocio',
            field=models.CharField(blank=True, choices=[('WALMART', 'Walmart'), ('AUTOZONE', 'Autozone'), ('MARCO_MORALES', 'Marco Morales')], max_length=20, null=True, verbose_name='Unidad de Negocio'),
        ),
    ]
