# Generated by Django 5.2.7 on 2025-10-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0037_unidad_cantidad_cilindros_unidad_tipo_combustible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(choices=[('S', 'Seca'), ('R', 'Refrigerada'), ('A', 'Refrigerada/Seca')], default='S', max_length=1, verbose_name='Tipo de Unidad'),
        ),
    ]
