# Generated by Django 5.2.7 on 2025-10-30 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0035_remove_entregasuministros_tipo_entrega_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoHerramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de Herramienta')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoMantenimientoCorrectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de Tarea Correctiva')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción (Opcional)')),
            ],
        ),
        migrations.CreateModel(
            name='HerramientaSolicitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mantenimiento.catalogoherramienta')),
            ],
        ),
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo')], max_length=20, verbose_name='Tipo de Mantenimiento')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas Adicionales (Admin)')),
                ('status', models.CharField(choices=[('ASIGNADA', 'Asignada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ASIGNADA', max_length=20, verbose_name='Estado')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de Tarea')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de Tarea')),
                ('tiempo_total_minutos', models.PositiveIntegerField(default=0, verbose_name='Duración Total (Minutos)')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('herramientas_solicitadas', models.ManyToManyField(related_name='tareas', through='mantenimiento.HerramientaSolicitada', to='mantenimiento.catalogoherramienta')),
                ('mantenimiento_correctivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.catalogomantenimientocorrectivo', verbose_name='Tarea Correctiva Específica')),
                ('tecnico', models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Tecnico'), ('groups__name', 'Supervisor'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='tareas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mantenimientos', to='flota.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Tarea de Mantenimiento',
                'verbose_name_plural': 'Tareas de Mantenimiento',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='herramientasolicitada',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.tareamantenimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='herramientasolicitada',
            unique_together={('tarea', 'herramienta')},
        ),
        migrations.CreateModel(
            name='TareaPreventivaSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subtask', models.CharField(choices=[('cambio_aceite', 'Cambio de aceite'), ('cambio_filtros', 'Cambio de filtros'), ('revision_general', 'Revisión general'), ('niveles', 'Niveles'), ('diferenciales', 'Diferenciales'), ('buges', 'Buges'), ('direccion', 'Dirección'), ('fugas_aire', 'Fugas de aire')], max_length=100, verbose_name='Sub-tarea')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('tarea_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks_preventivas', to='mantenimiento.tareamantenimiento')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('tarea_principal', 'nombre_subtask')},
            },
        ),
    ]
