# Generated by Django 5.2.7 on 2025-10-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareamantenimiento',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad'),
        ),
    ]
