# Generated by Django 5.2.7 on 2025-10-31 19:26

import mantenimiento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_tareamantenimiento_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareapreventivasubtask',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to=mantenimiento.models.ruta_evidencia_subtask, verbose_name='Foto de Evidencia'),
        ),
        migrations.AddField(
            model_name='tareapreventivasubtask',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones (ej: mm, psi, notas)'),
        ),
        migrations.AlterField(
            model_name='tareapreventivasubtask',
            name='nombre_subtask',
            field=models.CharField(choices=[('cambio_filtros', 'Cambios: Filtros (Aceite, combustible, aire)'), ('cambio_anticongelante', 'Cambios: Revisión de consistencia de anticongelante'), ('rev_gral_fusibles', 'Revisión General: Fusibles y relay'), ('rev_gral_luces', 'Revisión General: Luces'), ('rev_gral_fugas_aire', 'Revisión General: Fugas de aire'), ('rev_gral_llantas', 'Revisión General: Llantas (mm y psi)'), ('rev_gral_fugas_aceite', 'Revisión General: Fugas de aceite'), ('susp_amortiguadores', 'Suspensión: Amortiguadores'), ('susp_bolsas_aire', 'Suspensión: Bolsas de aire'), ('susp_bujes_muelle', 'Suspensión: Bujes de muelle'), ('susp_bujes_tirantes', 'Suspensión: Bujes de tirantes'), ('dir_vibracion', 'Dirección: Revisión de vibración (prueba de pistón)'), ('dir_pernos', 'Dirección: Revisión de pernos')], max_length=100, verbose_name='Sub-tarea'),
        ),
    ]
