# Generated by Django 5.2.7 on 2025-10-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_tareapreventivasubtask_foto_evidencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareapreventivasubtask',
            name='nombre_subtask',
            field=models.CharField(choices=[('camb_filtro', 'Cambio de filtro (Aceite, combustible y aire)'), ('camb_anticong', 'Revisión de consistencia de anticongelante'), ('gral_fusibles', 'Revisión, fusibles, relay'), ('gral_luces', 'Revisar luces'), ('gral_fugas_aire', 'Fugas de aire'), ('gral_llantas', 'Llantas (mm y psi)'), ('gral_fugas_aceite', 'Fugas de aceite'), ('susp_amortiguadores', 'Amortiguadores'), ('susp_bolsa_aire', 'Bolsa de aire'), ('susp_bujes_muelle', 'Bujes de muelle'), ('susp_bujes_tirantes', 'Bujes de tirantes'), ('dir_vibracion', 'Revisión de vibración (prueba de pistón)'), ('dir_pernos', 'Revisión de pernos')], max_length=100, verbose_name='Sub-tarea'),
        ),
    ]
