# Generated by Django 5.2.7 on 2025-10-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_alter_tareapreventivasubtask_nombre_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareapreventivasubtask',
            name='foto_evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/', verbose_name='Foto de Evidencia'),
        ),
    ]
